#!/bin/bash

# copy/paste files across directories (like click-to-copy/paste functionality in a file explorer)

BUFFER_FILE=/tmp/buffer-copy-files

copy () {
    #readlink -f "$@" > $BUFFER_FILE
    realpath "$@" > $BUFFER_FILE
}

paste () {
    while read -r f || [[ -n "$f" ]]; do
        [[ -e "$f" ]] && cp "$f" ./
    done < "$BUFFER_FILE"
}

show () {
    cat "$BUFFER_FILE"
}

op=$1
shift

case $op in
    c|copy)
        copy "$@"
        ;;
    p|paste)
        paste
        ;;
    s|show)
        show
        ;;
    *)
        echo "Unsupported operation $op"
        echo "$0 copy|paste files..."
        ;;
esac
