#! /usr/bin/env bash

# make a new directory and immediately move files into it

usage () {
    echo "Usage:"
    echo "	$(basename "$0") DIR FILE1 [FILE2 ...]"
    echo "		FILE1, FILE2 will be moved into new directory DIR"
    echo "		  FILE* may be specified as a glob"
}

_check () {
    if [[ "$#" -lt 2 ]]; then
        usage
        exit 1
    fi

    if [[ -e "$1" ]]; then
        echo "'$1': Already exists." 1>&2
        echo "(must create a directory with a unique name)" 1>&2
        exit 2
    fi
}

main () {
    local dir
    local -a files

    _check "$@"

    dir="$1"
    shift
    files=("$@")

    mkdir "$dir"
    for f in "${files[@]}"; do
        mv "$f" "$dir"
    done
}

main "$@"
