#! /usr/bin/env sh

# center the focused floating window.

main () {
    window="$(yabai -m query --windows --window)"
    display="$(yabai -m query --displays --window)"

    if [ "$(echo "$window" | jq '.floating')" -ne 1 ]; then
        echo "requires a floating window." >&2
        return 1
    fi

    coords="$(jq \
        --argjson window "${window}" \
        --argjson display "${display}" \
        -nr '(($display.frame | .x + .w / 2) - ($window.frame.w / 2) | tostring)
          + ":"
          + (($display.frame | .y + .h / 2) - ($window.frame.h / 2) | tostring)')"
    yabai -m window --move "abs:${coords}"
}

main "$@"
