#! /usr/bin/env sh

# Ensure the windows on a space given by $1 are tiled as 'monocle' (zoom-fullscreen)

# $YABAI_SPACE_ID, $YABAI_RECENT_SPACE_ID

main () {
    target="$1"

    if [ -z "$target" ]; then
        echo "requires target space" >&2
        return 1
    fi

    if ! command -v jq > /dev/null; then
        echo "requires jq" >&2
        return 1
    fi

    # add create/destroy rules if necessary:
    yabai -m signal --add event=window_created action="$0 $1" label=sustain-monocle-create-"$1"
    yabai -m signal --add event=window_destroyed action="$0 $1" label=sustain-monocle-destroy-"$1"

    yabai -m signal --add event=application_launched action="$0 $1" label=sustain-monocle-launch-"$1"
    yabai -m signal --add event=application_terminated action="$0 $1" label=sustain-monocle-terminate-"$1"

    if [ "$(yabai -m query --spaces --space | jq '.index')" = "$target" ]; then
        yabai -m query --windows --space \
            | jq 'map(select(.floating == 0 and ."zoom-fullscreen" == 0)) | .[].id' \
            | xargs -n1 -I{} yabai -m window {} --toggle zoom-fullscreen
    fi
}

main "$@"
